name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的默认分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'  # 更新为与你本地一致的 Node.js 版本

      - name: Clean up
        run: |
          rm -rf node_modules
          rm package-lock.json

      - name: Install dependencies
        run: npm ci  # 使用 npm ci 确保一致的依赖安装

      - name: Build project
        run: npm run build

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/**/*'
          message: 'Update docs directory with latest build'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          push: true
